# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(578, 613)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(9, 9, 105, 16))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(9, 28, 560, 101))
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(9, 135, 62, 16))
        self.label_3.setObjectName("label_3")
        self.te = QtWidgets.QTextEdit(self.centralwidget)
        self.te.setGeometry(QtCore.QRect(9, 154, 560, 102))
        self.te.setObjectName("te")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(9, 270, 115, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(9, 293, 119, 17))
        self.radioButton.setObjectName("radioButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 316, 146, 16))
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(9, 335, 141, 20))
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(9, 361, 560, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(9, 370, 113, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 390, 560, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(25, 497, 207, 16))
        self.label_4.setObjectName("label_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(25, 441, 531, 50))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout.addWidget(self.radioButton_6)
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(25, 516, 211, 20))
        self.spinBox_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(4)
        self.spinBox_2.setObjectName("spinBox_2")
        self.radioButton_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_1.setEnabled(True)
        self.radioButton_1.setGeometry(QtCore.QRect(247, 418, 191, 17))
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(44, 418, 197, 17))
        self.radioButton_4.setObjectName("radioButton_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(11, 561, 551, 23))
        self.pushButton.setObjectName("pushButton")
        self.spb_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spb_3.setGeometry(QtCore.QRect(282, 516, 37, 20))
        self.spb_3.setMinimum(1)
        self.spb_3.setObjectName("spb_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(247, 497, 108, 16))
        self.label_5.setObjectName("label_5")
        self.spb_4 = QtWidgets.QSpinBox(self.centralwidget)
        self.spb_4.setGeometry(QtCore.QRect(359, 516, 37, 20))
        self.spb_4.setMinimum(1)
        self.spb_4.setObjectName("spb_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(247, 516, 16, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(325, 516, 16, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(25, 399, 16, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 400, 94, 16))
        self.label_9.setObjectName("label_9")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(238, 497, 16, 58))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(402, 497, 167, 16))
        self.label_10.setObjectName("label_10")
        self.spb_5 = QtWidgets.QSpinBox(self.centralwidget)
        self.spb_5.setGeometry(QtCore.QRect(445, 516, 37, 20))
        self.spb_5.setMinimum(1)
        self.spb_5.setObjectName("spb_5")
        self.spb_6 = QtWidgets.QSpinBox(self.centralwidget)
        self.spb_6.setGeometry(QtCore.QRect(532, 516, 37, 20))
        self.spb_6.setMinimum(1)
        self.spb_6.setObjectName("spb_6")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(402, 516, 18, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(489, 516, 18, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(247, 542, 322, 16))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_13.setFont(font)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setObjectName("label_13")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 370, 101, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(200, 370, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.layoutWidget.raise_()
        self.label_2.raise_()
        self.textEdit.raise_()
        self.label_3.raise_()
        self.te.raise_()
        self.radioButton_3.raise_()
        self.radioButton.raise_()
        self.label.raise_()
        self.spinBox.raise_()
        self.line_2.raise_()
        self.radioButton_2.raise_()
        self.line_3.raise_()
        self.label_4.raise_()
        self.groupBox.raise_()
        self.spinBox_2.raise_()
        self.radioButton_1.raise_()
        self.radioButton_4.raise_()
        self.pushButton.raise_()
        self.spb_3.raise_()
        self.label_5.raise_()
        self.spb_4.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.line.raise_()
        self.label_10.raise_()
        self.spb_5.raise_()
        self.spb_6.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.pushButton_2.raise_()
        self.lineEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Парсер"))
        self.label_2.setText(_translate("MainWindow", "Поисковые запросы:"))
        self.label_3.setText(_translate("MainWindow", "Стоп-слова:"))
        self.radioButton_3.setText(_translate("MainWindow", "Сниппеты(Google)"))
        self.radioButton.setText(_translate("MainWindow", "Сниппеты(Яндекс)"))
        self.label.setText(_translate("MainWindow", "Глубина парсера сниппетов:"))
        self.radioButton_2.setText(_translate("MainWindow", "Картинки(Google)"))
        self.label_4.setText(_translate("MainWindow", "Сколько в заголовок пойдет сниппетов:"))
        self.groupBox.setTitle(_translate("MainWindow", "2. Способ сохранения:"))
        self.radioButton_5.setText(_translate("MainWindow", "noHTML"))
        self.radioButton_6.setText(_translate("MainWindow", "HTML"))
        self.radioButton_1.setText(_translate("MainWindow", "Картинки(Google)+текст(Google)"))
        self.radioButton_4.setText(_translate("MainWindow", "Картинки(Google) + текст(Яндекс)"))
        self.pushButton.setText(_translate("MainWindow", "Запустить парсер"))
        self.label_5.setText(_translate("MainWindow", "Количество абзацев:"))
        self.label_6.setText(_translate("MainWindow", "От"))
        self.label_7.setText(_translate("MainWindow", "До"))
        self.label_8.setText(_translate("MainWindow", "1."))
        self.label_9.setText(_translate("MainWindow", "Выбор источников:"))
        self.label_10.setText(_translate("MainWindow", "Количество сниппетов в абзаце:"))
        self.label_11.setText(_translate("MainWindow", "От:"))
        self.label_12.setText(_translate("MainWindow", "До:"))
        self.label_13.setText(_translate("MainWindow", "!Лучше поставить глубину парсера побольше, чтобы хватило!"))
        self.pushButton_2.setText(_translate("MainWindow", "Загрузить файл"))

